spring:
  application:
    name: backend

  # email配置
  mail:
    host: smtp.qq.com
    port: 465
    username: ${EMAIL_SENDER}
    password: ${EMAIL_PASSWORD} # 授权码
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

  # redis配置
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      timeout: 5s

  # mysql配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:deviceusagetime}?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  security:
    user:
      name: disabled
      password: disabled

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.primordialcode.backend.entity

logging:
  file:
    name: logs/backend.log
  level:
    org.springframework.security: DEBUG

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}